- `[x]` Create `src/containers/landing/LandingUseCases.tsx`
- `[x]` Update `src/app/[locale]/(landing)/page.tsx` to replace `LandingTestimonial` with `LandingUseCases`
- `[/]` Verify UI in browser
- `[ ]` Write `walkthrough.md`
