- [x] Identify IPv6/IPv4 connection hang (`netstat`)
- [x] Stop lingering `node` and `postgres` processes
- [x] Update `migration-runtime.ts` to use `localhost`
- [x] Fix non-cross-platform build commands (`cp -r`, `mkdir -p`)
- [x] Consolidate all loopback to `127.0.0.1` (IPv4)
- [x] Verify fixed startup via `run.bat`
