- [x] Add translations to `messages/en/client.json`
- [x] Add translations to `messages/vi/client.json`
- [x] Create `src/containers/landing/LandingContact.tsx`
- [x] Integrate `LandingContact` into `src/app/[locale]/(landing)/page.tsx` (Placed above FAQ)
- [x] Verify implementation in browser
