# Project Setup Task List

- [x] Clone the repository
- [x] Planning and initialization
    - [x] Verify `pnpm` installation
    - [x] Create implementation plan
- [x] Install dependencies
    - [x] Run `pnpm install` in the root directory
- [x] Configuration
    - [x] Check for `.env` requirements
- [x] Create startup batch file
- [x] Verification
    - [x] Run typecheck
    - [x] Verify UI and API are accessible
- [x] Enhance startup script
    - [x] Implement polling for health endpoint
    - [x] Automatically open browser
- [/] Debugging PGlite Startup
    - [x] Verify port 54330 is free
    - [x] Wipe directory `C:\Users\Admin\.paperclip\instances\default\db`
    - [/] Verify successful initialization
